### PR TITLE
Feature/update blacklight

### PR DESCRIPTION
**Pull request by ericgriffis**

### CODE REVIEW

**Comment by barnabyalter** [comment]
@ericgriffis Code changes look good, but there are some style changes that need to take place to align it with production. The ones I've noticed:

- Right pane sidebar headers are huge
- Spacing on left pane facet arrows
- Breadcrumbs should be ">" delimited
- Headers on advanced page

Functional issues:

- Search history and saved searches don't actually seem to work

**Comment by barnabyalter** [comment]
@ericgriffis needless to say, please include failing tests for the functional stuff

**Comment by ericgriffis** [comment]
@barnabyalter Definitely, I've written some failing tests already... trying to determine why they're failing...

**Comment by barnabyalter** [comment]
@ericgriffis only stupid thing I see (again no tests for this) is that they changed the header used for facet titles and that broke our javascript. ours should just have to be changed rom h5 to h3 here:

https://github.com/NYULibraries/findingaids/blob/feature/update_blacklight/app/assets/javascripts/popovers.js.coffee.erb#L12-L15

**Comment by ericgriffis** [comment]
@barnabyalter fixed and added a feature for it

**Pull request merged**
