### PR TITLE
Feature/bookmark export

### PR DESCRIPTION
**Pull request by eshadatta**
@barnabyalter ,

Thanks for your comments on the previous branch. I messed up some commits and so deleted that branch. I incorporated your feedback into my changes. However, I'm running into a cuke issue. When I test to see if the user has checked the bookmark, there's some ajax action happening, where we get a brief message saying "Saving" until the bookmark shows that it is checked and the label changes to "In Bookmarks". In capybara, the test hangs because it's waiting for something. When I did a save_and_open_page on that, I saw that the label has changed to "Saving...". I was wondering if you had any tips on how to go forward? I tried following [these steps](https://robots.thoughtbot.com/automatically-wait-for-ajax-with-capybara) and got a little further but not too far. I got other errors and instead of disappearing into another rabbit hole, I figured I'd ask you how to go forward. Thanks.

### CODE REVIEW

**Comment by eshadatta** [comment]
Figured out how to do the ajax timeout, courtesy of [this](https://robots.thoughtbot.com/automatically-wait-for-ajax-with-capybara). Continuing with writing tests.

**Comment by eshadatta** [comment]
@barnabyalter , @NYULibraries/finding-aids ,
I have another cucumber test question. So, the tests now cover clicking on a checkbox and seeing that the "Your Bookmarks(1)" count has gone up. I now need to see the bookmarks themselves and test the hover action to get the tooltips when I mouse over the Email and Cite links. I noticed: 

1. when test clicks on "Your Bookmarks" to go to bookmarks, there are no bookmarks in the page. This is probably another session thing. I'm not quite sure what to google. If you have any insight, I'd appreciate it.
2. Rspec test in application controller is failing because it's looking for a user "dev123". But if the db is not seeded, it won't find it. When I try to "create" a user using a factory by doing the following:
```cucumber
   describe "#current_user_dev" do 
       let(:user) { create(:user) }
       subject(:user) { controller.current_user_dev }
       it { should be_instance_of(User) }
       it { expect(user.username).to eql("dev123") }
   end
```
It still fails.
Thanks for your help.

Esha

**Comment by barnabyalter** [comment]
@eshadatta You might want to try changing FactoryGirl.build to FatoryGirl.create so that the user persists. 

The separate scenarios are:

```cucumber
Scenario: Adding a bookmark
  Given I am logged in
  When I search on the phrase “…”
  And I click on “Save Bookmark” within the result “”
  Then that record should be saved in my bookmarks

Scenario: Citing bookmarks
  Given I am logged in 
  And I am on the “Bookmarks” page
  And I have “title” saved in my booksmarks
  When I click “Cite”
  Then I should see a citation in the following format:
    <TABLE>

Scenario: Sharing bookmarks 
  Given I am logged in
  And I am on the “Bookmarks” page
  And I have “title” saved in my booksmarks
  When I click “Email”
  Then I should receive an email in the following format:
    <TABLE>
```

So you are testing each piece of functionality separately.  When you assume that you have bookmarks then that’s creating a factory for bookmarks

Consider using a mock ActionMailer function to pull the last email sent since it won’t actually send an email, e.g:

```ruby
def last_email
   ActionMailer::Base.deliveries[-1]
end
```

**Comment by eshadatta** [comment]
@barnabyalter ,

Thanks for your feedback. FactoryGirl.build doesn't help in this case though. I just pushed up the latest code. I'll add in your scenario changes soon, right now I'm just trying to see if the session persists if I change urls, and it doesn't. Apparently, I also thought my RSpec tests were passing but it's still failing the application controller test. I'm trying to build a user through FactoryGirl for rspec and that's also failing.

**Comment by eshadatta** [comment]
@barnabyalter ,
Couple more questions:
1. When I ran rspec on everything and I had changed features/support/login.rb to FactoryGirl.create, I got some rspec errors saying that "Email" was already taken.
```
Failures:

  1) contact information returns the Contact information page
     Failure/Error: get "/help/contact_information"
     ActionView::Template::Error:
       Validation failed: Email has already been taken, Username has already been taken
     # ./features/support/login.rb:6:in `current_user'
     # ./spec/requests/contact_information_request_spec.rb:5:in `block (2 levels) in <top (required)>'

  2) search tips returns the Search tips page
     Failure/Error: expect(response.status).to be == 200
       expected: == 200
            got:    302
     # ./spec/requests/search_tips_request_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 16.33 seconds
237 examples, 2 failures

Failed examples:

rspec ./spec/requests/contact_information_request_spec.rb:4 # contact information returns the Contact information page
rspec ./spec/requests/search_tips_request_spec.rb:4 # search tips returns the Search tips page

```
When I changed it back to build and changed my bookmark step for logged in user to FactoryGirl.create, rspec ran fine. I am still not getting the "saved" bookmark when I have capybara go to the bookmarks page. I was wondering if I should create a Bookmarks factory and just use that with an existing solr doc factory (and add more fields to the solr doc) to continue with my cuke test. If you have any other suggestions, please let me know. 

Also, on my local machine, the rspec test for applicationcontroller_spec passes; however, it doesn't seem to in the build. I was wondering if you had any insight into this as well. If all this can be cleared up by meeting for 15 - 30 minutes, please let me know. I am definitely keeping the cuke test changes you had suggested in mind and will make those changes, I wanted to move forward with these other questions first.

Thanks.

Esha

**Comment by ekate** [comment]
Hi Esha,

Do you have other tests which needs to create user  and run before this one
? Check how the user is created. When you use "create", rspec tries to save
the user in the db so name/email must be unique.Build doesn't touch db so
name/email could be anything. Sorry if it is irrelevant.

Kate

On Tue, Apr 7, 2015 at 4:10 PM, eshadatta <notifications@github.com> wrote:

> @barnabyalter <https://github.com/barnabyalter> ,
> Couple more questions:
> 1. When I ran rspec on everything and I had changed
> features/support/login.rb to FactoryGirl.create, I got some rspec errors
> saying that "Email" was already taken.
>
> Failures:
>
>   1) contact information returns the Contact information page
>      Failure/Error: get "/help/contact_information"
>      ActionView::Template::Error:
>        Validation failed: Email has already been taken, Username has already been taken
>      # ./features/support/login.rb:6:in `current_user'
>      # ./spec/requests/contact_information_request_spec.rb:5:in `block (2 levels) in <top (required)>'
>
>   2) search tips returns the Search tips page
>      Failure/Error: expect(response.status).to be == 200
>        expected: == 200
>             got:    302
>      # ./spec/requests/search_tips_request_spec.rb:6:in `block (2 levels) in <top (required)>'
>
> Finished in 16.33 seconds
> 237 examples, 2 failures
>
> Failed examples:
>
> rspec ./spec/requests/contact_information_request_spec.rb:4 # contact information returns the Contact information page
> rspec ./spec/requests/search_tips_request_spec.rb:4 # search tips returns the Search tips page
>
>
> When I changed it back to build and changed my bookmark step for logged in
> user to FactoryGirl.create, rspec ran fine. I am still not getting the
> "saved" bookmark when I have capybara go to the bookmarks page. I was
> wondering if I should create a Bookmarks factory and just use that with an
> existing solr doc factory (and add more fields to the solr doc) to continue
> with my cuke test. If you have any other suggestions, please let me know.
>
> Also, on my local machine, the rspec test for applicationcontroller_spec
> passes; however, it doesn't seem to in the build. I was wondering if you
> had any insight into this as well. If all this can be cleared up by meeting
> for 15 - 30 minutes, please let me know. I am definitely keeping the cuke
> test changes you had suggested in mind and will make those changes, I
> wanted to move forward with these other questions first.
>
> Thanks.
>
> Esha
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NYULibraries/findingaids/pull/57#issuecomment-90716716>
> .
>



-- 
Ekaterina Pechekhonova
Digital Library Programmer/Analyst
New York University
Libraries
email: ekate@nyu.edu
phone: 212-992-9993

**Comment by eshadatta** [comment]
@ekate ,

Thanks so much for your reply. The rspec applicationcontroller_spec and the cucumber test are the only tests where I need a user. Originally, the login.rb had FactoryGirl.build to create a user for some other rspec tests, but I need create as the applicationcontroller is doing a find_by_username, so it needs to save it into the db. I need to create a user for it to persist through the session for my cucumber tests. So, I've been explicitly calling the create method for my tests.

**Comment by ekate** [comment]
Hi Esha,

I just check that email and name are sequential. Thus there must be some
problems with sequence reset or database cleanup

Kate

On Wed, Apr 8, 2015 at 2:04 PM, Ekaterina Pechekhonova <ekate@nyu.edu>
wrote:

> Hi Esha,
>
> Do you have other tests which needs to create user  and run before this
> one ? Check how the user is created. When you use "create", rspec tries to
> save the user in the db so name/email must be unique.Build doesn't touch db
> so name/email could be anything. Sorry if it is irrelevant.
>
> Kate
>
> On Tue, Apr 7, 2015 at 4:10 PM, eshadatta <notifications@github.com>
> wrote:
>
>> @barnabyalter <https://github.com/barnabyalter> ,
>> Couple more questions:
>> 1. When I ran rspec on everything and I had changed
>> features/support/login.rb to FactoryGirl.create, I got some rspec errors
>> saying that "Email" was already taken.
>>
>> Failures:
>>
>>   1) contact information returns the Contact information page
>>      Failure/Error: get "/help/contact_information"
>>      ActionView::Template::Error:
>>        Validation failed: Email has already been taken, Username has already been taken
>>      # ./features/support/login.rb:6:in `current_user'
>>      # ./spec/requests/contact_information_request_spec.rb:5:in `block (2 levels) in <top (required)>'
>>
>>   2) search tips returns the Search tips page
>>      Failure/Error: expect(response.status).to be == 200
>>        expected: == 200
>>             got:    302
>>      # ./spec/requests/search_tips_request_spec.rb:6:in `block (2 levels) in <top (required)>'
>>
>> Finished in 16.33 seconds
>> 237 examples, 2 failures
>>
>> Failed examples:
>>
>> rspec ./spec/requests/contact_information_request_spec.rb:4 # contact information returns the Contact information page
>> rspec ./spec/requests/search_tips_request_spec.rb:4 # search tips returns the Search tips page
>>
>>
>> When I changed it back to build and changed my bookmark step for logged
>> in user to FactoryGirl.create, rspec ran fine. I am still not getting the
>> "saved" bookmark when I have capybara go to the bookmarks page. I was
>> wondering if I should create a Bookmarks factory and just use that with an
>> existing solr doc factory (and add more fields to the solr doc) to continue
>> with my cuke test. If you have any other suggestions, please let me know.
>>
>> Also, on my local machine, the rspec test for applicationcontroller_spec
>> passes; however, it doesn't seem to in the build. I was wondering if you
>> had any insight into this as well. If all this can be cleared up by meeting
>> for 15 - 30 minutes, please let me know. I am definitely keeping the cuke
>> test changes you had suggested in mind and will make those changes, I
>> wanted to move forward with these other questions first.
>>
>> Thanks.
>>
>> Esha
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/NYULibraries/findingaids/pull/57#issuecomment-90716716>
>> .
>>
>
>
>
> --
> Ekaterina Pechekhonova
> Digital Library Programmer/Analyst
> New York University
> Libraries
> email: ekate@nyu.edu
> phone: 212-992-9993
>



-- 
Ekaterina Pechekhonova
Digital Library Programmer/Analyst
New York University
Libraries
email: ekate@nyu.edu
phone: 212-992-9993

**Comment by eshadatta** [comment]
@ekate ,

Hmm..ok, I should clear the db before and after running rspec, then?

**Comment by ekate** [comment]
Uniqeness should be ensured by use of sequence, but on Travis something
goes wrong. For that to work we need to ensure database cleanup and
sequence reset are in sync. I don't know how it's done on Travis. To avoid
this problem I would just use a permanent user name instead on relying on
sequence.

e.g. insted of calling this:
FactoryGirl.define do factory :user do sequence(:username) {|n| "test123#{n}
"} sequence(:email) { |n| "test123#{n}@library.edu" } end

 Use something  like this in user factory:
factory :user_dev, class:User do username "dev123" email "
dev.loper@library.edu" end


> @ekate <https://github.com/ekate> ,
>
> Thanks so much for your reply. The rspec applicationcontroller_spec and
> the cucumber test are the only tests where I need a user. Originally, the
> login.rb had FactoryGirl.build to create a user for some other rspec tests,
> but I need create as the applicationcontroller is doing a find_by_username,
> so it needs to save it into the db. I need to create a user for it to
> persist through the session for my cucumber tests. So, I've been explicitly
> calling the create method for my tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NYULibraries/findingaids/pull/57#issuecomment-90992789>
> .
>



-- 
Ekaterina Pechekhonova
Digital Library Programmer/Analyst
New York University
Libraries
email: ekate@nyu.edu
phone: 212-992-9993

**Comment by ekate** [comment]
If sequence is reset before each build then yes, but I think db is cleaned
by Travis before each ran too... Probably there are some other issues with
sequence... Probably try to just create a user with specific name like
Barnaby does for dev_user here :
spec/factories/user.rb

On Wed, Apr 8, 2015 at 2:18 PM, eshadatta <notifications@github.com> wrote:

> @ekate <https://github.com/ekate> ,
>
> Hmm..ok, I should clear the db before and after running rspec, then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NYULibraries/findingaids/pull/57#issuecomment-90993852>
> .
>



-- 
Ekaterina Pechekhonova
Digital Library Programmer/Analyst
New York University
Libraries
email: ekate@nyu.edu
phone: 212-992-9993

**Comment by eshadatta** [comment]
@ekate ,
Hmm..ok, I'll try that. I had created the dev user factory actually. Initially, I had a problem with cuke tests with that and Barnaby actually asked me to create a sequence, but let me check again to see if I run into issues. Thanks again!

**Comment by ep54** [comment]
@eshadatta 
I understand why it's better to use sequence- any user should be able to do bookmarks, but with specific user name you can check if problem was with sequence.
Just in case. Here is an example on how I did it in Ichabod:
I created admin user in user.rb factor:
factory :admin do
      username "test_admin"
      email "test_admin@nyu.edu"
    end
the create a test_user_helper.rb method in spec/support/helpers:
module SpecTestHelper
  def create_or_return_test_admin
    @user ||= create(:admin)
  end
end

and then use it in controller  spec:
require 'support/test_user_helper'

describe NyucoresController do

  let(:user) { create_or_return_test_admin }
  before  { controller.stub(:current_user).and_return(user) }

**Comment by eshadatta** [comment]
Awesome, thanks so much. I'll check it out.

**Comment by eshadatta** [comment]
@jgpawletko , @ekate, 

So, I'm still running into the same issues.

**Rspec issue**
If I don't seed the database, rspec test for application controller fails. Sometimes, mysteriously(the db isn't cleared out or whatever) it works even if I don't seed the db. Since I am not seeding the db in rspec before I start, the test fails. I have a factory girl create invocation before I start the rspec test for application controller, but it is somehow not creating the user for the rspec test to pass.

**Cucumber issue**
1. I changed the cuke test to reflect the steps Barnaby had outlined above in this PR. When I look at the test log, I see an insert statement to see that the bookmark is saved. Also, I notice that the user id is persisting in that step definition. However, I don't see the bookmarks when I visit that path. On closer inspection of the views in the blacklight gem, it seems that in cucumber, the @documentlist var isn't being populated in the test. I tried doing a bookmark factory and I see that is being created too but it doesn't populate the bookmark.
2. I have been working on this test for over a week. This functionality has already been tested within blacklight. I basically just turned it on. It works on my dev machine. Do I need to test the "email" and "cite" functionality especially since no matter what I have done, I can not get the saved bookmark to show up. I do show that I can "save" the bookmark.

Do you guys have any proposals for my rspec and/or cucumber dilemmas? Thanks so much for your time.

**Comment by jgpawletko** [comment]
@eshadatta @ekate 
Hi Esha,
I'll take a look and see if I can help.

**Comment by eshadatta** [comment]
@jgpawletko , thanks, I appreciate it

**Comment by jgpawletko** [comment]
@eshadatta 
Hi Esha,

I was able to get your RSpec examples "green" by changing [this code](https://github.com/NYULibraries/findingaids/blob/feature/bookmark_export/spec/controllers/application_controller_spec.rb#L60-L66) 

to:
```
  describe "#current_user_dev" do                                                                                                          
    before(:each)  { FactoryGirl.create(:user_dev) }                                                                                       
    subject        { controller.current_user_dev }                                                                                         
    it             { should be_instance_of(User) }                                                                                         
    its(:username) { should be == "dev123" }                                                                                               
  end                                                                                                                                      
```

Please let me know if you have any questions, comments, or concerns.

**Comment by eshadatta** [comment]
@jgpawletko , sweet! Thanks! Good to know about "before"

**Comment by eshadatta** [comment]
@barnabyalter , @NYULibraries/finding-aids 
I have fixed the rspec per @jgpawletko 's suggestion. I still have remaining questions about cuke tests.

As mentioned earlier(I'm copying from an earlier comment)

1. I changed the cuke test to reflect the steps Barnaby had outlined above in this PR. When I look at the test log, I see an insert statement to see that the bookmark is saved. Also, I notice that the user id is persisting in that step definition. However, I don't see the bookmarks when I visit that path. On closer inspection of the views in the blacklight gem, it seems that in cucumber, the @documentlist var isn't being populated in the test which means that the saved bookmark isn't shown on that page. I tried doing a bookmark factory and I see that is being created too but it doesn't populate the bookmark.
2. I have been working on this test for over a week. This functionality has already been tested within blacklight. I basically just turned it on. It works on my dev machine. Do I need to test the "email" and "cite" functionality especially since no matter what I have done, I can not get the saved bookmark to show up. I do show that I can "save" the bookmark.
3. I have a citation helper function for which I have a rspec test. I can add other fields to it to make it match the acceptance criteria. Right now, it gets the correct format for the citation with the fields that are present in the solr doc. Please let me know about the direction of the cucumber tests.

Thanks.

Esha

**Comment by jgpawletko** [comment]
@eshadatta 
I will look at the Cukes later today.

**Comment by eshadatta** [comment]
@jgpawletko ,
Thanks so much, Joe, I really appreciate it.

**Comment by sallyvermaaten** [comment]
@barnabyalter @eshadatta 

I'm clearly no expert on cucumber testing but I wonder if these tests on the bookmark, citation and email functions fall under the category we discussed in our last sprint planning meeting - i.e. they are essentially re-testing functionality already tested in the Blacklight application itself? It sounds like they may be, in which case I'd be happy to be say let's not worry about cucumbers for these - especially since they're proving so tricky - and let's rely on some user spot checking against the acceptance criteria instead. I try to do spot checking before accepting a story in any case. I'd be happy to note that spot checking is required in the acceptance criteria / comments for the story. 

Barnaby - does that approach make sense or does it sound problematic? 

Thanks!
Sally

**Comment by barnabyalter** [comment]
@sallyvermaaten @eshadatta I think this is an important integration test and we should be able to confirm that bookmarks are working consistently across upgrades. I'll take a look and send a pull request.

**Comment by sallyvermaaten** [comment]
@barnabyalter @eshadatta Okay thanks, Barnaby.

**Comment by eshadatta** [comment]
@barnabyalter ok, cool. Thanks so much for looking into it. I am very curious about the solution. :-)

**Comment by jgpawletko** [comment]
@eshadatta 
Hi Esha,
I started to look at this, but for some reason my configuration went wonky and even the `development` branch is `red` on my machine.  I'll take a look after I get `development` is `green` again.
Best-
Joe

**Comment by ckassel** [comment]
@eshadatta I think your code is cursed!

On Mon, Apr 13, 2015 at 11:00 PM, Joseph Pawletko <notifications@github.com>
wrote:

> @eshadatta <https://github.com/eshadatta>
> Hi Esha,
> I started to look at this, but for some reason my configuration went wonky
> and even the development branch is red on my machine. I'll take a look
> after I get development is green again.
> Best-
> Joe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NYULibraries/findingaids/pull/57#issuecomment-92573300>
> .
>



-- 
Carol Kassel
Senior Manager, Digital Library Infrastructure
NYU Digital Library Technology Services
cmk@nyu.edu
(212) 992-9246
dlib.nyu.edu

**Comment by eshadatta** [comment]
Yes, I'm the opposite of Midas. :-) Joe, that happened to me too. I had to stop and start Jetty for some reason.

**Pull request closed without merging**
